<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonTeamRepository extends EntityRepository implements RepositoryInterface
{
}
