app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_player:
    resource: "@AppBundle/Controller/PlayerController.php"
    type: rest
