# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    domain.repository.player:
        class: AppBundle\Repository\PlayerRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - AppBundle\Entity\Player

    domain.usecase.query.search_player:
        class: AppBundle\Usecase\SearchPlayerUsecase
        arguments: [ '@domain.repository.player' ]

    domain.criteria_builder.search_player:
        class: AppBundle\Entity\Criteria\SearchPlayerCriteriaBuilder
